version = 1

[[annotations]]
path = [
 ".formatter.exs",
 ".github/CODEOWNERS",
 ".github/workflows/ci.yml",
 ".gitignore",
 "CHANGELOG.md",
 "NOTICE",
 "REUSE.toml",
 "mix.exs",
 "mix.lock",
 "VERSION"
]
precedence = "aggregate"
SPDX-FileCopyrightText = "None"
SPDX-License-Identifier = "CC0-1.0"

[[annotations]]
path = [
 "README.md"
]
precedence = "aggregate"
SPDX-FileCopyrightText = "2016 Frank Hunleth"
SPDX-License-Identifier = "CC-BY-4.0"

# Buildroot derived or related files
[[annotations]]
path = [
 "Config.in",
 "package/**",
 "external.mk",
 "nerves_defconfig",
 "post-build.sh",
 "post-createfs.sh"
]
precedence = "aggregate"
SPDX-FileCopyrightText = "The Buildroot developers <buildroot@buildroot.org>"
SPDX-License-Identifier = "GPL-2.0-or-later"

# Linux kernel derived or related files
[[annotations]]
path = [
 "linux-6.6.defconfig",
]
precedence = "override"
SPDX-FileCopyrightText = "Various"
SPDX-License-Identifier = "GPL-2.0-only"

# Fwup config files
[[annotations]]
path = [
 "fwup-ops.conf",
 "fwup.conf",
 "fwup_include/*"
]
precedence = "aggregate"
SPDX-FileCopyrightText = "None"
SPDX-License-Identifier = "CC0-1.0"

# Various config files
[[annotations]]
path = [
 "busybox.fragment",
 "cmdline.txt",
 "config.txt",
 "grub.cfg",
 "rootfs_overlay/etc/boardid.config",
 "rootfs_overlay/etc/erlinit.config",
 "rootfs_overlay/etc/fw_env.config"
]
precedence = "aggregate"
SPDX-FileCopyrightText = "None"
SPDX-License-Identifier = "CC0-1.0"
